version: "3"

includes:
  k8s:
    taskfile: ./deploy/k8s/taskfile.yaml
    dir: ./deploy/k8s

env:
  SPIKE_OTLP_ENDPOINT: http://localhost:4318/v1/metrics
  SPIKE_OTLP_SERVICE_NAMESPACE: bitkit
  SPIKE_OTLP_SERVICE_NAME: my-node-otel-spike

vars:
  APP_NAME: wsgw-e2e-app
  NAMESPACE: '{{.NAMESPACE | default "wsgw-e2e" }}'
  HTTP2: '{{.HTTP2 | default "false"}}'

tasks:
  app-version-data:
    cmds:
      - |
        cd app
        project_root=..
        build_root=./dist
        application="WebSocket Gateway / End-to-end Test / Test Application"
        version=$(jq -r '.version' $project_root/package.json || :)
        commit=$(git rev-parse HEAD)

        mkdir -p "$build_root"

        cat > $build_root/version.json <<EOF
        {
            "application": "$application",
            "version": "$version",
            "commit": "$commit",
            "buildTime": "{{now}}"
        }
        EOF
  app:
    deps: [app-version-data]
    cmds:
      - |
        tsc -p app
        cp ./package*.json ./app/dist/
        cp ./app/dist/version.json ./app/image/
        bun build --target node --external="$(jq -r '.dependencies|keys[]' package.json)" ./app/dist/app/src/index.js --outfile ./app/image/bundle.js --sourcemap=none
    sources:
      - app/src/**/*
    generates:
      - app/dist/bundle.js
  app:image:
    deps: [app]
    cmds:
      - |
        docker_dir=app/image
        cp ./package.json ./package-lock.json $docker_dir/
        if which minikube && minikube status;
        then
            eval "$(minikube docker-env)"
        fi
        docker build -t bitkit/{{.APP_NAME}}-node $docker_dir
  run:
    deps: [app-version-data]
    cmds:
      - tsc -p app
      - |
        password_base=crixcrax

        pwcreds="["
        for nummer in $(seq 1 30); do
          if test $nummer -gt 1; then
            pwcreds="${pwcreds},"
          fi
          pwcreds="${pwcreds}{\"username\":\"user${nummer}\",\"password\":\"${password_base}${nummer}\"}"
        done
        pwcreds="${pwcreds}]"

        export E2EAPP_SERVER_PORT=45678
        export E2EAPP_PASSWORD_CREDENTIALS="$pwcreds"
        export E2EAPP_WSGW_HOST=localhost
        export E2EAPP_WSGW_PORT=45679
        export E2EAPP_HTTP2={{.HTTP2}}
        node app/dist/app/src/index.js
  smoke-test:
    cmds:
      - tsc -p client
      - bun run client/dist/client/src/smoke-test.js
